FROM golang:1.17

# install dev candy
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

# actual work goes here
COPY . .

CMD ["air"]
