version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/src
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=postgres
